run:
  deadline: 120s
linters:
  enable:
    - govet
    - golint
    - ineffassign
    - goconst
    - deadcode
    - gofmt
    - goimports
    - gosec
    - gosimple
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - bodyclose
    - dogsled
    - goprintffuncname
    - misspell
    - prealloc
    - exportloopref
    - stylecheck
    - unconvert
    - gocritic
  disable-all: true
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - scopelint
        - bodyclose
        - unconvert
        - gocritic
        - gosec
    # If we have tests in shared test folders, these can be less strictly linted
    - path: tests/.*_tests\.go
      linters:
        - golint
        - bodyclose
        - stylecheck
