run:
  deadline: 120s
linters:
  enable:
    - govet
    - ineffassign
    - goconst
    - gofmt
    - goimports
    - gosec
    - gosimple
    - staticcheck
    - typecheck
    - unused
    - bodyclose
    - dogsled
    - goprintffuncname
    - misspell
    - prealloc
    - copyloopvar
    - stylecheck
    - unconvert
    - gocritic
    - revive
  disable-all: true
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - scopelint
        - bodyclose
        - unconvert
        - gocritic
        - gosec
        - goconst
        - revive
    - path: _test\.go
      linters:
        - revive
      text: "dot-imports:"
    # If we have tests in shared test folders, these can be less strictly linted
    - path: tests/.*_tests\.go
      linters:
        - revive
        - bodyclose
        - stylecheck
