FROM mcr.microsoft.com/vscode/devcontainers/go:0-1.19

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Uninstall pre-installed formatting and linting tools
# They would conflict with our pinned versions
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    git \
    make \
    pre-commit \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && chmod -R a+w /go/pkg

WORKDIR /workspaces

# Set the default shell to bash instead of sh
ENV SHELL /bin/bash
