name: Configuration support
description: Configuration problems and overall requests on how to properly use oauth2-proxy.
title: "[Support]: <Short description>"
labels: ["configuration", "help wanted"]
body:
  - type: input
    attributes:
      label: OAuth2-Proxy Version
      description: Which version of oauth2-proxy are you using?
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Provider
      description: Which identity provider are you using?
      options:
        - adfs
        - azure
        - bitbucket
        - digitalocean
        - facebook
        - gitea
        - github
        - gitlab
        - google
        - keycloak
        - keycloak-oidc
        - linkedin
        - logingov
        - nextcloud
        - oidc
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current Behaviour of your Problem
      description: Tell us what you expect to happen and what happens instead.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Configuration details or additional information
      description: |
        Please share more details about your environment and how you configured oauth2-proxy.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        1. With this config...
        1. Run '...'
        1. See error...
    validations:
      required: false

