name: E2E

on:
  issue_comment:
    types: [created]

jobs:
  e2e:
    uses: oauth2-proxy/e2e-suite/.github/workflows/e2e.yml@main
    permissions:
      contents: read
      statuses: write
      issues: write
      pull-requests: write
