name: Just Release

on:
  push:
    tags:
      - '*'        # any tag

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v6

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to ${{ vars.REGISTRY }}
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME_NIGHTLY }}
        password: ${{ secrets.REGISTRY_PASSWORD_NIGHTLY }}

    - name: Build images
      run: |
        make build-docker-all

    - name: Push images
      run: |
        make push-docker-all
