name: Nightly builds

on:
  schedule: # Run every day at 03:00 UTC
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # only run this build in the main repository, not in forks
    if: github.repository == 'oauth2-proxy/oauth2-proxy'
    steps:
    - name: Check out code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        ref: master
        fetch-depth: 0
        fetch-tags: true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

    - name: Login to quay.io
      uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
      with:
        registry: quay.io/oauth2-proxy
        username: ${{ secrets.REGISTRY_USERNAME_NIGHTLY }}
        password: ${{ secrets.REGISTRY_PASSWORD_NIGHTLY }}

    - name: Build images
      run: |
        make nightly-build

    - name: Push images
      run: |
        make nightly-push
